name: Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "5 * * * *"
on: [workflow_dispatch]

jobs:
  Release:
    name: Release

    runs-on: macOS-latest

    steps:

      - name: init
        uses: actions/checkout@v1
      
#       - name: get sha
#         id: sha
#         shell: bash
#         run: echo "::set-output name=value::$(cat sha.txt)"

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b main --depth 1 ${{secrets.GIT_ADDRESS}} .
        shell: bash

      - name: get package
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: version
     
  tools:
    needs: [Release]

    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, macOS-12, macOS-latest, windows-latest]

    steps:
      - name: init
        uses: actions/checkout@master

      - name: set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: set python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" 

#       - name: get sha
#         id: sha
#         shell: bash
#         run: echo "::set-output name=value::$(cat sha.txt)"

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone -b main --depth 1 ${{secrets.GIT_ADDRESS}} .
        shell: bash

      - name: install
        run: |
         npm i

#       - name: install electron-builder with macos latest
#         if: startsWith(matrix.os, 'macOS')
#         run: npm i electron-builder@21.2.0

      - name: build
        run: npm run build

      - name: get package version
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: ./package.json
          key: version

      - name: get package productName
        id: package1
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: productName

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.package.outputs.version}}
          name: v${{steps.package.outputs.version}}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          append_body: true
          files: |
            release/${{steps.package.outputs.version}}/*.exe
            release/${{steps.package.outputs.version}}/*.msi
            release/${{steps.package.outputs.version}}/latest.yml
            release/${{steps.package.outputs.version}}/*.dmg
            release/${{steps.package.outputs.version}}/*.zip
            release/${{steps.package.outputs.version}}/*.AppImage
            release/${{steps.package.outputs.version}}/*.pkg
            release/${{steps.package.outputs.version}}/latest-mac.yml
            release/${{steps.package.outputs.version}}/*.deb
            release/${{steps.package.outputs.version}}/*.rpm
            release/${{steps.package.outputs.version}}/*.apk
            release/${{steps.package.outputs.version}}/latest-linux.yml


#       - name: deploy
#         run: npm run upload:null

          
      # - name: Remove builder-debug.yml
      #   shell: bash
      #   run: |
      #     [ -f ./build/builder-debug.yml ] && rm ./build/builder-debug.yml
          
      # - name: Upload Prerelease
      #   uses: Ireoo/upload-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.cache.outputs.upload_url }}
      #     dir: build
      #     exts: '["exe", "dmg", "zip", "AppImage", "deb", "rpm", "apk", "msi", "pkg", "appx", "yml"]'
      #     suffix: _tools
          
#       - name: Upload to tools.integem.com
#         run: npm run upload
